name: worpalox
description: "WORPALOX: English-Russian word-order puzzle game"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/corpus/
